FROM node:20-alpine AS build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ARG REACT_APP_DASHBOARD_ID
ARG REACT_APP_SUPERSET_DOMAIN
ENV REACT_APP_DASHBOARD_ID=$REACT_APP_DASHBOARD_ID
ENV REACT_APP_SUPERSET_DOMAIN=$REACT_APP_SUPERSET_DOMAIN

RUN npm run build

FROM nginx:alpine AS production
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]