name: Build and Deploy Spring Boot Microservices

on:
  push:
    branches:
      - develop

env:
  DOCKER_USERNAME: dnjau
  DOCKER_PASSWORD: Sc281-6736/2014
  SSH_PORT: 22

  SSH_PASS: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}

  CONTAINER_NAME: chanjo
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/chanjo:latest

jobs:
  build_microservice_:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build React app
        run: |
          npm install
          npm run build

      - name: Display build logs
        run: cat /home/runner/.npm/_logs/2024-01-06T17_40_51_494Z-debug.log || echo "No build logs found"

      - name: Build & push Docker image
        run: |
          echo '${{ env.DOCKER_PASSWORD }}' | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker buildx create --use --name workflowBuilder
          docker buildx build --platform=linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME }} --push .
          docker logout