name: React App Deployment # name of the workflo

on:
  push:
    branches:
      - develop # branch name

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: example # environment variable

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build & push  Docker image
        run: |
          docker login -u dnjau -p Sc281-6736/2014
          docker buildx create --use --name workflowBuilder
          docker buildx build --platform=linux/amd64,linux/arm64 -t ${{ env.IMAGE_NAME_ }} --push .
          docker logout